# Generated by Django 3.2.5 on 2024-07-16 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='reach',
        ),
    ]
